### PR TITLE
WIP: Save to PDF

### PR DESCRIPTION
**Pull request by asinghvi17**
Rebased on master.  Let's see if this works, will need tests as well...

### CODE REVIEW

**Comment by asinghvi17** [comment]
Seems to work without issue on the simple tests (btw: those aren't tested).

**Comment by asinghvi17** [comment]
It "works", but the tests are annoyingly failing with several different bugs (after I expanded their horizons a little).  I consider this working as of now, though.

**Comment by asinghvi17** [comment]
will add tests later.

**Comment by grero** [comment]
Thanks for getting this merged!

**Pull request merged**
