### PR TITLE
The latest text layouting branch

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
@jkrumbiegel any reason you closed this?

**Comment by asinghvi17** [comment]
Everything that fails here is marker_offset related, which I fixed in my refactor.

**Comment by jkrumbiegel** [comment]
No that was after I merged the other branch, I somehow confused this branch for the other branch in Gitkraken and thought that needed to be deleted, then noticed my mistake a second later and restored from local. Device scale and scale text 🙈

**Comment by asinghvi17** [comment]
Cool, no worries.  Will rebase on master and merge.

**Pull request merged**
